version: '2.1'

networks:

  gwnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          ip_range: 172.30.0.0/24
          # gateway: 172.30.0.254

  clients:
    enable_ipv6: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: fd30:252e:b4f5::/64
          ip_range: fd30:252e:b4f5:0:1::/80
          # gateway: fd30:252e:b4f5::1/64
          # aux_addresses:
          #   nat64: "fd30:252e:b4f5:0:1::1"
        - subnet: 172.29.0.0/24
          ip_range: 172.29.0.0/24
          gateway: 172.29.0.1

services:

  nat64:
    build:
      context: test
    privileged: true
    stdin_open: true
    networks:
      gwnet:
        ipv4_address: 172.30.0.2
      clients:
        ipv4_address: 172.29.0.2
        # ipv6_address: fd30:252e:b4f5::2/64

  ubuntu:
    image: creatordev/docker-nat64-client
    privileged: true
    stdin_open: true
    networks:
      clients: {}
    depends_on:
    - nat64

  alpine:
    image: alpine-curl
    privileged: true
    build:
      context: alpine-curl
    stdin_open: true
    entrypoint: /set-gateway.sh
    command:
      - "172.29.0.2"
      - "fd30:252e:b4f5:0:1::1"
      - ash
    networks:
      clients: {}
    depends_on:
    - nat64
    - ubuntu # just to make IP addresses correct for the fdfd:: routing <cough>
